//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public string title { get; set; }
        public string description { get; set; }
        public string projectName { get; set; }
        public string assignee { get; set; }
        public string priority { get; set; }
        public string status { get; set; }
        public string type { get; set; }
        public int id { get; set; }
    }
}
